version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todoapidocker:
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"
    depends_on:
      pgsqldb:
        condition: service_healthy
    volumes:
      - "./:/usr/src/app"
  pgsqldb:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    networks:
      - app-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
